### ISSUE TITLE
Parser chokes on field attributes

### ISSUE THREAD

**Issue by magnet** [butte-rs/butte#23]
The current parser seems unable to accept field attributes (apparently named metadata in `butte-build`?). I had a quick try to fix this, but I have no experience with nom 5. @cpcloud maybe you have an idea?

Here's an example of a schema failing to parse:
```
table HelloReply {
  message: string (required);
}
```

**Comment by cpcloud** [comment]
I thought I had implemented this, so this might be a bug.

**Comment by lovesegfault** [comment]
@cpcloud Go to sleep
