### ISSUE TITLE
Preserve doc comments

### ISSUE THREAD

**Issue by reyk** [butte-rs/butte#36]
The spec supports `///` doc comments:

> May be written as in most C-based languages. Additionally, a triple comment (///) on a line by itself signals that a comment is documentation for whatever is declared on the line after it (table/struct/field/enum/union/element), and the comment is output in the corresponding C++ code. Multiple such lines per item are allowed.

It would be nice to preserve them in the output.

Additionally, butte fails with doc comments before fields:

```
Error: Parse was incomplete: not parsed: table MyTable {
    /// foo
   ...
```

**Comment by cpcloud** [comment]
Should have a PR up for this this weekend.
