### ISSUE TITLE
Missing `Default` implementation for generated `*Args`

### ISSUE THREAD

**Issue by reyk** [butte-rs/butte#38]
flatc generates `Default` implementations for the table args. This is especially useful with many fields or when using defaults in the schema.

For example:

```
table Foo {                                                                                           
  a: int;                                                                                             
  b: int;                                                                                             
  c: int = 3;                                                                                
  d: string;                                                                                          
  e: string (required);                                                                               
}                                                                                                     
```

`flatc`:

```rust
pub struct FooArgs<'a> {
    pub a: i32,
    pub b: i32,
    pub c: i32,
    pub d: Option<flatbuffers::WIPOffset<&'a  str>>,
    pub e: Option<flatbuffers::WIPOffset<&'a  str>>,
}
impl<'a> Default for FooArgs<'a> {
    #[inline]
    fn default() -> Self {
        FooArgs {
            a: 0,
            b: 0,
            c: 3,
            d: None,
            e: None, // required field
        }
    }
}
```

`butte`:

```rust
pub struct FooArgs<'a> {
    pub a: i32,
    pub b: i32,
    /// The default value for this field is __3i64__
    pub c: i32,
    pub d: Option<butte::WIPOffset<&'a str>>,
    pub e: butte::WIPOffset<&'a str>,
}
```

**Comment by magnet** [comment]
This is done on purpose if one of the fields is required.  I don't think flatc's approach is correct as `Default` should not be implemented on types that don't have an obvious default.

Instead, I suggest this pattern: you can put all required fields together in a table `Foo` and have a single optional field named `options` with type `FooOptions` in which all fields are optional.  This patterns works well in Rust in general.

When `Default` *can* be implemented on an `*Args` type, `butte-build` will generate the correct implementation.

Another way I want to depart from `flatc` is have non-required scalars generated in `Option`.  The difference between `scalar` and `non-scalar` is not obvious to end-users and should not influence the generated code so much.

In general the goal of `butte` IMO should definitely not be to mimic `flatc`, on the contrary I'm looking at improving the ergonomics, safety and API.

**Comment by reyk** [comment]
Thanks for the explanation, “`Default` should not be implemented on types that don't have an obvious default” makes sense and I will try it with moving the required fields out as suggested.

**Comment by reyk** [comment]
Cool, (re-)moving the “required” field works and I get the defaults now.
