### ISSUE TITLE
Bug with PR#25 "Use i128 to represent integers"

### ISSUE THREAD

**Issue by reyk** [butte-rs/butte#46]
Hi,

the PR https://github.com/butte-rs/butte/pull/25 has (exposed) a bug, for example:

```
table Hello {
    value: int64 = 0;
}
```

Now uses an `i128` for the default values in the Rust code even with the type being `i64`:

```Rust
fn add_value(&mut self, value: i64) {
    self.fbb.push_slot::<i64>(Hello::VT_VALUE, value, 0i128);
}
```

**Comment by cpcloud** [comment]
Thanks for the report. Looks like we don't have a test for this.
