### ISSUE TITLE
"missing required field value" with optional value

### ISSUE THREAD

**Issue by reyk** [butte-rs/butte#47]
Hi,

I'm not quite sure if this is a bug or if I'm doing something wrong. With the following definition:

```
table Hello {
    value: string;
}
```

I get a the `Option` and a `Default` implementation as expected:
```rust
pub struct HelloArgs<'a> {
    pub value: Option<butte::WIPOffset<&'a str>>,
}
impl<'a> Default for HelloArgs<'a> {
  fn default() -> Self {
    Self { value: None }
  }
}
```

But it now fails on runtime with the `missing required field value` error. I think it is related to the fact that the `create()` method only calls the internal `add_value()` method if the field is `Some` but the `finish()` step fails because `Hello::VT_VALUE` is not set.

```rust
        if let Some(x) = args.value {
            builder.add_value(x);
        }
```
...`add_value()` sets the `Hello::VT_VALUE` slot...
```rust
        self.fbb.required(o, Hello::VT_VALUE, "value");
```

**Comment by magnet** [comment]
Yeah this is definitely a bug, I forgot to update the call to the builder when adding support for optional fields.

I'll finish adding some more tests that include *compile* + *runtime* tests to make sure it works end-to-end and can be used in a small crate, and fix this!  Thanks for all the bug reports!

**Comment by reyk** [comment]
My pull request #49 is just a quick fix as it doesn't include new tests. But the output matches what I get from flatc.
